### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

### ISSUE THREAD

**Issue by izzatum** [getkeops/keops#200]
Hi, 

I just installed the keops. However, when I tested the installation, I received the following error. Could you help me with this?

Thanks!

`
pykeops.test_torch_bindings()    # perform the compilation
[pyKeOps] Initializing build folder for dtype=float32 and lang=torch in /home/izzatum/.cache/pykeops-1.5-cpython-39-gpu0 ... [pyKeOps] Initializing build folder for dtype=float32 and lang=torch in /home/izzatum/.cache/pykeops-1.5-cpython-39-gpu0 ... Traceback (most recent call last):
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/test/install.py", line 62, in test_torch_bindings
    my_conv(x, y).view(-1), torch.tensor(expected_res).type(torch.float32)
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/torch/generic/generic_red.py", line 568, in __call__
    out = GenredAutograd.apply(
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/torch/generic/generic_red.py", line 47, in forward
    myconv = LoadKeOps(
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/keops_io.py", line 48, in __init__
    self._safe_compile()
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/utils.py", line 75, in wrapper_filelock
    func_res = func(*args, **kwargs)
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/keops_io.py", line 53, in _safe_compile
    check_or_prebuild(self.dtype, self.lang, self.include_dirs)
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/compile_routines.py", line 176, in check_or_prebuild
    run_and_display(
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/utils.py", line 168, in run_and_display
    proc = subprocess.run(
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/test/install.py", line 74, in test_torch_bindings
    print(my_conv(x, y))
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/torch/generic/generic_red.py", line 568, in __call__
    out = GenredAutograd.apply(
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/torch/generic/generic_red.py", line 47, in forward
    myconv = LoadKeOps(
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/keops_io.py", line 48, in __init__
    self._safe_compile()
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/utils.py", line 75, in wrapper_filelock
    func_res = func(*args, **kwargs)
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/keops_io.py", line 53, in _safe_compile
    check_or_prebuild(self.dtype, self.lang, self.include_dirs)
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/compile_routines.py", line 176, in check_or_prebuild
    run_and_display(
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/pykeops/common/utils.py", line 168, in run_and_display
    proc = subprocess.run(
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
`

**Comment by izzatum** [comment]
Installed cmake, yet another error came out.
