### ISSUE TITLE
Changes between 1.1.2 and 1.1.1?

### ISSUE THREAD

**Issue by KeAWang** [getkeops/keops#21]
After the update from 1.1.1 to 1.1.2, I'm having issues with using keops on two different computers when running the basic installation code:
```
import torch
import pykeops.torch as pktorch

x = torch.arange(1, 10, dtype=torch.float32).view(-1, 3)
y = torch.arange(3, 9, dtype=torch.float32).view(-1, 3)

my_conv = pktorch.Genred('SqNorm2(x-y)', ['x = Vi(3)', 'y = Vj(3)'])
print(my_conv(x, y))
```

On one device, I'm getting 
```
>>> import torch
>>> import pykeops.torch as pktorch
>>> 
>>> x = torch.arange(1, 10, dtype=torch.float32).view(-1, 3)
>>> y = torch.arange(3, 9, dtype=torch.float32).view(-1, 3)
>>> 
>>> my_conv = pktorch.Genred('SqNorm2(x-y)', ['x = Vi(3)', 'y = Vj(3)'])
>>> print(my_conv(x, y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/miniconda3/envs/gpytorch/lib/python3.6/site-packages/pykeops/torch/generic/generic_red.py", line 351, in __call__
    out = GenredAutograd.apply(self.formula, self.aliases, backend, self.dtype, device_id, ranges, *args)
  File "/home/alex/miniconda3/envs/gpytorch/lib/python3.6/site-packages/pykeops/torch/generic/generic_red.py", line 21, in forward
    ['-DPYTORCH_INCLUDE_DIR=' + ';'.join(include_dirs)]).import_module()
  File "/home/alex/miniconda3/envs/gpytorch/lib/python3.6/site-packages/pykeops/common/keops_io.py", line 52, in import_module
    return importlib.import_module(self.dll_name)
  File "/home/alex/miniconda3/envs/gpytorch/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
```

On another device, I'm getting
```
>>> import torch
>>> import pykeops.torch as pktorch
7.4.0
>>> 
>>> x = torch.arange(1, 10, dtype=torch.float32).view(-1, 3)
>>> y = torch.arange(3, 9, dtype=torch.float32).view(-1, 3)
>>> 
>>> my_conv = pktorch.Genred('SqNorm2(x-y)', ['x = Vi(3)', 'y = Vj(3)'])
>>> print(my_conv(x, y))
Compiling libKeOpstorch91c92bd508 in /home/alex_w/.cache/pykeops-1.1.2-cpython-37//build-libKeOpstorch91c92bd508:
       formula: Sum_Reduction(SqNorm2(x-y),1)
       aliases: x = Vi(0,3); y = Vj(1,3); 
       dtype  : float32
... CMake Error at pybind11/tools/FindPythonLibsNew.cmake:127 (message):
  Python config failure: Python is 0-bit, chosen compiler is 64-bit
Call Stack (most recent call first):
  pybind11/tools/pybind11Tools.cmake:16 (find_package)
  pybind11/CMakeLists.txt:33 (include)



--------------------- CMAKE DEBUG -----------------
Command '['cmake', '/home/alex_w/miniconda3/envs/rl/lib/python3.7/site-packages/pykeops', '-DCMAKE_BUILD_TYPE=Release', '-DFORMULA_OBJ=Sum_Reduction(SqNorm2(x-y),1)', '-DVAR_ALIASES=auto x = Vi(0,3); auto y = Vj(1,3); ', '-Dshared_obj_name=libKeOpstorch91c92bd508', '-D__TYPE__=float', '-DPYTHON_LANG=torch', '-DC_CONTIGUOUS=1', '-DPYTORCH_INCLUDE_DIR=/home/alex_w/miniconda3/envs/rl/lib/python3.7/site-packages/torch/include;/home/alex_w/miniconda3/envs/rl/lib/python3.7/site-packages/torch/include/torch/csrc/api/include', '-DcommandLine=cmake /home/alex_w/miniconda3/envs/rl/lib/python3.7/site-packages/pykeops -DCMAKE_BUILD_TYPE=Release -DFORMULA_OBJ=Sum_Reduction(SqNorm2(x-y),1) -DVAR_ALIASES=auto x = Vi(0,3); auto y = Vj(1,3);  -Dshared_obj_name=libKeOpstorch91c92bd508 -D__TYPE__=float -DPYTHON_LANG=torch -DC_CONTIGUOUS=1 -DPYTORCH_INCLUDE_DIR=/home/alex_w/miniconda3/envs/rl/lib/python3.7/site-packages/torch/include;/home/alex_w/miniconda3/envs/rl/lib/python3.7/site-packages/torch/include/torch/csrc/api/include']' returned non-zero exit status 1.
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Compute properties automatically set to: -DMAXIDGPU=7;-DMAXTHREADSPERBLOCK0=1024;-DSHAREDMEMPERBLOCK0=49152;-DMAXTHREADSPERBLOCK1=1024;-DSHAREDMEMPERBLOCK1=49152;-DMAXTHREADSPERBLOCK2=1024;-DSHAREDMEMPERBLOCK2=49152;-DMAXTHREADSPERBLOCK3=1024;-DSHAREDMEMPERBLOCK3=49152;-DMAXTHREADSPERBLOCK4=1024;-DSHAREDMEMPERBLOCK4=49152;-DMAXTHREADSPERBLOCK5=1024;-DSHAREDMEMPERBLOCK5=49152;-DMAXTHREADSPERBLOCK6=1024;-DSHAREDMEMPERBLOCK6=49152;-DMAXTHREADSPERBLOCK7=1024;-DSHAREDMEMPERBLOCK7=49152
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- The CUDA Host CXX Compiler: /usr/bin/c++
-- Autodetected CUDA architecture(s): 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5 
-- Using shared_obj_name: libKeOpstorch91c92bd508
-- Found PythonInterp: /home/alex_w/miniconda3/envs/rl/bin/python3.7 (found version "3.7.4") 
-- Configuring incomplete, errors occurred!
See also "/home/alex_w/.cache/pykeops-1.1.2-cpython-37/build-libKeOpstorch91c92bd508/CMakeFiles/CMakeOutput.log".
See also "/home/alex_w/.cache/pykeops-1.1.2-cpython-37/build-libKeOpstorch91c92bd508/CMakeFiles/CMakeError.log".

--------------------- ----------- -----------------
make: *** No rule to make target 'libKeOpstorch91c92bd508'.  Stop.

--------------------- MAKE DEBUG -----------------
Command '['cmake', '--build', '.', '--target', 'libKeOpstorch91c92bd508', '--', 'VERBOSE=1']' returned non-zero exit status 2.

--------------------- ----------- -----------------
Done.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex_w/miniconda3/envs/rl/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 351, in __call__
    out = GenredAutograd.apply(self.formula, self.aliases, backend, self.dtype, device_id, ranges, *args)
  File "/home/alex_w/miniconda3/envs/rl/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 21, in forward
    ['-DPYTORCH_INCLUDE_DIR=' + ';'.join(include_dirs)]).import_module()
  File "/home/alex_w/miniconda3/envs/rl/lib/python3.7/site-packages/pykeops/common/keops_io.py", line 52, in import_module
    return importlib.import_module(self.dll_name)
  File "/home/alex_w/miniconda3/envs/rl/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'libKeOpstorch91c92bd508'
```

I'm wondering if anything about the builds changed between 1.1 and 1.2? Also how can I go about getting debugging these issues? I tried `PYKEOPS_VERBOSE=1` and clearing the cache, but it hasn't given me any additional debug information.

**Comment by bcharlier** [comment]
Hi Alex,

1) on your first device, the error message is not clear to me... try to remove pykeops (pip uninstall pykeops), remove all cache and reinstall it (pip install pykeops).

2) On your second device the error :
```
... CMake Error at pybind11/tools/FindPythonLibsNew.cmake:127 (message):
  Python config failure: Python is 0-bit, chosen compiler is 64-bit
Call Stack (most recent call first):
  pybind11/tools/pybind11Tools.cmake:16 (find_package)
  pybind11/CMakeLists.txt:33 (include)
```

   is due to a wrong config in your venv (cmake doe not find the correct python lib for some reasons). The best thing to do may be to reset the venv by reinstalling it... :(
 
good luck;

b.

**Comment by KeAWang** [comment]
Thanks for the help! I still haven't been able to resolve this, but I'll come back to this later.

**Comment by KeAWang** [comment]
I happened to reinstall my ArchLinux setup and it fixed the first problem as a byproduct... Not sure why.

But for anyone stumbling on this issue, I had to lower the gcc version to gcc-8 to compile pykeops because it looks like CUDA 10.1 is not compatible with gcc-9, which is what my system was on.

You can do this by installing gcc-8
```
export CC=/usr/bin/gcc-8 (or whatever your path is)
export CXX=/usr/bin/g++-8 (or whatever your path is)
```

**Comment by KeAWang** [comment]
Turns out it's an issue with anaconda not playing well with gcc 9 and overshadowing the `ld` bin:
https://github.com/pytorch/pytorch/issues/16683
https://github.com/ContinuumIO/anaconda-issues/issues/11152
