### ISSUE TITLE
Running pykeops on docker container without access to cuda folder

### ISSUE THREAD

**Issue by HuuDatDo** [getkeops/keops#291]
I'm trying to run pykeops on a docker container connected to a GPUs server that hides the cuda folder. I tried to install the conda environment from #85 as well as the .conda folder but none of them worked. Are there any other ways to run pykeops on this kind of system?

`<stdin>:1:10: fatal error: cuda.h: No such file or directory
compilation terminated.
[KeOps] Warning : 
    The location of Cuda header files cuda.h and nvrtc.h could not be detected on your system.
    You must determine their location and then define the environment variable CUDA_PATH,
    either before launching Python or using os.environ before importing keops. For example
    if these files are in /vol/cuda/10.2.89-cudnn7.6.4.38/include you can do :
      import os
      os.environ['CUDA_PATH'] = '/vol/cuda/10.2.89-cudnn7.6.4.38'
      import pykeops
    
[KeOps] Compiling main dll ... /home/ubuntu/miniconda3/envs/pykeops_env/lib/python3.10/site-packages/keops/binders/nvrtc/keops_nvrtc.cpp:5:10: fatal error: nvrtc.h: No such file or directory
    5 | #include <nvrtc.h>
      |          ^~~~~~~~~
compilation terminated.
OK
Traceback (most recent call last):
  File "/home/ubuntu/22dat.dh/NODE/STSum/test.py", line 5, in <module>
    import pykeops
  File "/home/ubuntu/miniconda3/envs/pykeops_env/lib/python3.10/site-packages/pykeops/__init__.py", line 35, in <module>
    cppyy.include(os.path.join(cuda_include_path, "nvrtc.h"))
  File "/home/ubuntu/miniconda3/envs/pykeops_env/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by jeanfeydy** [comment]
Hi @HuuDatDo,

Could you tell us more about the way CUDA is "hidden" to Docker?
We maintain a reference Docker image: https://hub.docker.com/r/getkeops/keops-full
Which is documented here: https://github.com/getkeops/keops/blob/main/Dockerfile

(I will update it soon to catch up with the latest version of PyTorch.)

Install instructions and a typical use case (= rendering the www.kernel-operations.io website) are described here: http://kernel-operations.io/keops/python/installation.html#using-docker-or-singularity.

Best regards,
Jean

**Comment by HuuDatDo** [comment]
Hi @jeanfeydy 

Thank you so much for your reply!

According to my lab manager, I'm not allowed to run anything related to cuda because it would affect other users, the cuda folder is not visible to any docker, so in the path 'usr/local/' there is no cuda folder. I still can run nvidia-smi so it should exist. I will ask again if I can create a new docker based on the documentation. 

Best,
Huu Dat

**Comment by HuuDatDo** [comment]
Hi @jeanfeydy 

Thanks to your instructions, I could build a new container and define the cuda path. However, when I run `pykeops.test_numpy_bindings()`, I encountered this bug: 

`ImportError: /root/.cache/keops2.1/build/pykeops_nvrtc.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv`

Do you know any solutions to fix this because some previous similar issues were fixed with pykeops version 1.4.2?

Best,
Huu Dat
