### ISSUE TITLE
KeyError: 'nvrtc'

### ISSUE THREAD

**Issue by 2363776628** [getkeops/keops#368]
Traceback (most recent call last):
  File "/public/home/naoep_cbgc_gjd/songp/UnsupervisedSelectiveLabeling-main/selective_labeling/usl-imagenet.py", line 62, in <module>
    d_knns, ind_knns = utils.partitioned_kNN(
  File "/public/home/naoep_cbgc_gjd/songp/UnsupervisedSelectiveLabeling-main/selective_labeling/utils/nn_utils.py", line 224, in partitioned_kNN
    ind_knn, d_knn = kNN(x_train, x_test, K=K)
  File "/public/home/naoep_cbgc_gjd/songp/UnsupervisedSelectiveLabeling-main/selective_labeling/utils/nn_utils.py", line 190, in kNN
    d_knn, ind_knn = D_ij.Kmin_argKmin(K, dim=1, backend="GPU")
  File "/public/home/naoep_cbgc_gjd/anaconda3/envs/sl3/lib/python3.10/site-packages/pykeops/common/lazy_tensor.py", line 2161, in Kmin_argKmin
    return self.reduction("KMin_ArgKMin", opt_arg=K, axis=axis, dim=dim, **kwargs)
  File "/public/home/naoep_cbgc_gjd/anaconda3/envs/sl3/lib/python3.10/site-packages/pykeops/common/lazy_tensor.py", line 746, in reduction
    return res()
  File "/public/home/naoep_cbgc_gjd/anaconda3/envs/sl3/lib/python3.10/site-packages/pykeops/common/lazy_tensor.py", line 930, in __call__
    return self.callfun(*args, *self.variables, **self.kwargs)
  File "/public/home/naoep_cbgc_gjd/anaconda3/envs/sl3/lib/python3.10/site-packages/pykeops/torch/generic/generic_red.py", line 624, in __call__
    out = GenredAutograd.apply(
  File "/public/home/naoep_cbgc_gjd/anaconda3/envs/sl3/lib/python3.10/site-packages/pykeops/torch/generic/generic_red.py", line 78, in forward
    myconv = keops_binder["nvrtc" if tagCPUGPU else "cpp"](
KeyError: 'nvrtc'

**Comment by jeanfeydy** [comment]
Hi @2363776628 ,

Thanks for your interest in our library.
This issue generally pops up when CUDA is installed in a non-standard location, which is often the case on academic clusters. As explained [here](https://github.com/getkeops/keops/issues/257#issuecomment-1184624579), you may fix this using the `CUDA_PATH` environment variable.

If you have trouble locating `nvrtc.h` on your system, please feel free to re-open the issue with more information about your configuration.
Best regards,
Jean
