### ISSUE TITLE
PyTorch test script fails

### ISSUE THREAD

**Issue by JadTawil-theonly** [getkeops/keops#38]
Hello.

I pass the numpy test script, but not the pyTorch. I get the following output:

`(venv) jad@jad-Aspire-A717-71G ~/venv $ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch

>>> import pykeops.torch as pktorch
>>> 
>>> x = torch.arange(1, 10, dtype=torch.float32).view(-1, 3)
>>> y = torch.arange(3, 9, dtype=torch.float32).view(-1, 3)
>>> 
>>> my_conv = pktorch.Genred('SqNorm2(x-y)', ['x = Vi(3)', 'y = Vj(3)'])
>>> print(my_conv(x, y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jad/venv/lib/python3.5/site-packages/pykeops/torch/generic/generic_red.py", line 351, in __call__
    out = GenredAutograd.apply(self.formula, self.aliases, backend, self.dtype, device_id, ranges, *args)
  File "/home/jad/venv/lib/python3.5/site-packages/pykeops/torch/generic/generic_red.py", line 21, in forward
    ['-DPYTORCH_INCLUDE_DIR=' + ';'.join(include_dirs)]).import_module()
  File "/home/jad/venv/lib/python3.5/site-packages/pykeops/common/keops_io.py", line 52, in import_module
    return importlib.import_module(self.dll_name)
  File "/home/jad/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /home/jad/.cache/pykeops-1.2-cpython-35/libKeOpstorch91c92bd508.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv
`

**Comment by JadTawil-theonly** [comment]
Basically, what version of Pytorch do you use? Do you build from source? If so can you send me the exact version so i can do the same.

**Comment by bcharlier** [comment]
Hi @JadTawil-theonly ,

The C++ api of pytorch as changed a lot between the pytorch 0.4 and pytorch 1.0. So we (try to) follow the last stable version of pytorch: please consider using the last packaged version of pytorch (v1.3).

b.
