### ISSUE TITLE
Sample Test and GeomLoss Sample Error

### ISSUE THREAD

**Issue by VElysianP** [getkeops/keops#40]
Hello,

Thank you very much for your amazing work!

I am running in Ubuntu 18.04.3. I installed Python3.7 using Anaconda. Then I installed CUDA 10.1 and Pytorch, and then KeOps. I did not receive any error when I install pykeops. But when I tested installation, I passed none of the scripts. 

The error message from the Pytorch script was:

> /usr/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
> #error -- unsupported GNU version! gcc versions later than 6 are not supported!
> ^~~~~
> CMake Error at keopslibKeOpstorch91c92bd508_generated_link_autodiff.cu.o.Release.cmake:219 (message):
> Error generating
> /home/velysianp/.cache/pykeops-1.2-cpython-37/build-
> libKeOpstorch91c92bd508/CMakeFiles/keopslibKeOpstorch91c92bd508.dir/keops/core/./keopslibKeOpstorch91c92bd508_generated_link_autodiff.cu.o
> 
> make[3]: *** [CMakeFiles/keopslibKeOpstorch91c92bd508.dir/keops/core/keopslibKeOpstorch91c92bd508_generated_link_autodiff.cu.o] Error 1
> make[2]: *** [CMakeFiles/keopslibKeOpstorch91c92bd508.dir/all] Error 2
> make[1]: *** [CMakeFiles/libKeOpstorch91c92bd508.dir/rule] Error 2
> make: *** [libKeOpstorch91c92bd508] Error 2

I checked my system with ` gcc --version `, and it returned gcc-7.4.0 which seems to be Ubuntu 18.04.3 x86_64 default. So I am not sure what should I do with this error. 

Then I also received error when I tried to run sample code from GeomLoss:

> Traceback (most recent call last):
> File "plot_optimal_transport_2D.py", line 149, in <module> gradient_descent( SamplesLoss("sinkhorn", p=2, blur=.1) )
> File "plot_optimal_transport_2D.py", line 107, in gradient_descent L_αβ = loss(x_i, y_j)
> File "/home/me/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
> result = self.forward(*input, **kwargs)
> File "/home/me/anaconda3/lib/python3.7/site-packages/geomloss/samples_loss.py", line 237, in forward verbose = self.verbose )
> File "/home/me/anaconda3/lib/python3.7/site-packages/geomloss/sinkhorn_samples.py", line 102, in sinkhorn_online C_xx, C_yy, C_xy, C_yx, ε_s, ρ, debias=debias )
> File "/home/me/anaconda3/lib/python3.7/site-packages/geomloss/sinkhorn_divergence.py", line 151, in sinkhorn_loop a_x = λ * softmin(ε, C_xx, α_log ) # OT(α,α)
> File "/home/me/anaconda3/lib/python3.7/site-packages/geomloss/sinkhorn_samples.py", line 69, in softmin_online
> return - ε * log_conv( x, y, f_y.view(-1,1), torch.Tensor([1/ε]).type_as(x) ).view(-1)
> File "/home/me/anaconda3/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 351, in __call__ out = GenredAutograd.apply(self.formula, self.aliases, backend, self.dtype, device_id, ranges, *args)
> File "/home/me/anaconda3/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 43, in forward *args)
> RuntimeError: [KeOps] This KeOps shared object has been compiled without cuda support: try to set tagHostDevice to 0 or recompile the formula with a working version of cuda.

Also, I checked my CUDA and Pytorch installation, it turned out that they are working all right. So I am really curious what should I do with those errors? 

Thank you very much!
Elyson

**Comment by VElysianP** [comment]
Problem solved with reinstall Ubuntu and driver as well as CUDA 10.2. Also, for the installation of KeOps, I found it would be better to use git clone than pip install, since it is easier for me to cmake and change the parameters inside cmake. Anyway, thank you very much for your amazing work!
