### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by lelayf** [getkeops/keops#43]
```
(Py37A) C:\Users\Francois>pip install pykeops
Collecting pykeops
  Downloading https://files.pythonhosted.org/packages/48/72/d1576e0841b1fa6dd65de4ef203362e5eb7748215005ace2975e12ac2679/pykeops-1.3.tar.gz (301kB)
     |████████████████████████████████| 307kB 731kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\francois\venvs\py37a\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Francois\\AppData\\Local\\Temp\\pip-install-hm6v38ko\\pykeops\\setup.py'"'"'; __file__='"'"'C:\\Users\\Francois\\AppData\\Local\\Temp\\pip-install-hm6v38ko\\pykeops\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Francois\AppData\Local\Temp\pip-install-hm6v38ko\pykeops\pip-egg-info'
         cwd: C:\Users\Francois\AppData\Local\Temp\pip-install-hm6v38ko\pykeops\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Francois\AppData\Local\Temp\pip-install-hm6v38ko\pykeops\setup.py", line 11, in <module>
        from pykeops import __version__ as current_version
      File "C:\Users\Francois\AppData\Local\Temp\pip-install-hm6v38ko\pykeops\pykeops\__init__.py", line 34, in <module>
        from .common.utils import clean_pykeops
      File "C:\Users\Francois\AppData\Local\Temp\pip-install-hm6v38ko\pykeops\pykeops\common\utils.py", line 1, in <module>
        import fcntl
    ModuleNotFoundError: No module named 'fcntl'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

(Py37A) C:\Users\Francois>pip install fcntl
ERROR: Could not find a version that satisfies the requirement fcntl (from versions: none)
ERROR: No matching distribution found for fcntl
```

a litlle more search shows that `fcntl` is only supported on Mac/Linux. It seems it is only used in one place to lock a file, which could be done in a more portable way with [`portalocker`](https://pypi.org/project/portalocker/)?

**Comment by fradav** [comment]
Hello, there is a development branch 4f1e6bac60e8f83abe3e15842d4bc235e1b69b52 which solves this issue, but this isn't the only one. Pure C++ or numpy part of keops works fine for now.
Pytorch linking is still WIP.
I will update this issue, stay tuned.

**Comment by fradav** [comment]
On hold : due to quarantine, I lost my access to a gpu for windows for testing the port.

**Comment by shaheenahmedc** [comment]
Hi All, 

You may have seen my mention for this issue above. 

PyKeOps is a dependancy in a recently released Gaussian Process Regression package, and I was just wondering if installing the above development branch will provide me with a Windows compatible version? 

Apologies if you haven't managed to get round to it yet @fradav.

**Comment by scottgigante** [comment]
Windows support for this package would be much appreciated! Just posting to affirm that there is interest.

**Comment by fradav** [comment]
Hi all, 

I'm onto it again, thanks for your patience

**Comment by fradav** [comment]
Due to various reasons, I'm withdrawing from the project from now on, starting a brand new project with similar goals.

Regards,

**Comment by MSensale** [comment]
Hi All! 
I've also been trying to install the software in Windows and found the same error reported by @lelayf. It is about the installation of the package pykeops. It also failed because it could not find the 'fcntl' module.

I have seen the requirements for the installation of pykeops, and they should be satisfied on my machine. I have just installed MinGW as a g++ version >=7 C++ compiler, and I still have the same error. 

If anyone had some updates on this issue, that would be great. 

__________________________________________________________________________________________________________________________________
Collecting deformetrica
  Using cached deformetrica-4.3.0-py3-none-any.whl (244 kB)
Collecting pykeops==1.4.1
  Using cached pykeops-1.4.1.tar.gz (319 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [10 lines of output]
  Traceback (most recent call last):
    File "<string>", line 36, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\msensale\AppData\Local\Temp\pip-install-v0oz6g98\pykeops_515e4f98cea345da8414e9fd01f89f0a\setup.py", line 11, in <module>
      from pykeops import __version__ as current_version
    File "C:\Users\msensale\AppData\Local\Temp\pip-install-v0oz6g98\pykeops_515e4f98cea345da8414e9fd01f89f0a\pykeops\__init__.py", line 34, in <module>
      from .common.utils import clean_pykeops
    File "C:\Users\msensale\AppData\Local\Temp\pip-install-v0oz6g98\pykeops_515e4f98cea345da8414e9fd01f89f0a\pykeops\common\utils.py", line 1, in <module>
      import fcntl
  ModuleNotFoundError: No module named 'fcntl'
  [end of output]

**Comment by lostmsu** [comment]
@fradav is Windows WIP available somewhere?
What is your new project?

**Comment by ancestor-mithril** [comment]
What is the status of this issue? Is there any plan for adding Windows support for pykeops?

**Comment by jeanfeydy** [comment]
Hi @ancestor-mithril,

Thanks for your interest in the library!
KeOps works fully on WSL, and @initialneil was kind enough to write a pull request for native support (#281).
I am currently in the process of integrating it - but you may want to try it now, as in #297.
Please feel free to let us know if you face any issue: we don't have much experience with Windows, and welcome any user feedback.

Best regards,
Jean

**Comment by An-u-rag** [comment]
Hi @jeanfeydy, thank you for continuing to work on Windows Integration.

I have tried the steps mentioned in #281 but I encountered an error. Would appreciate any help regarding this, thanks!

![image](https://user-images.githubusercontent.com/58253865/228393133-0be33afa-18c9-4c16-ad99-1628c63e21b1.png)

**Comment by initialneil** [comment]
Hi @An-u-rag, can you provide the cuda, pytorch version that you tested?
If you can use VSCode to debug step-by-step with F11, you can step to the codes around "Cuda libraries were not detected" to see why so.
More information would help to identify what's not working.

**Comment by An-u-rag** [comment]
Thanks for the reply @initialneil.  Pytorch version  is 1.13.1 and Cuda version is 11.7.

![image](https://user-images.githubusercontent.com/58253865/228431397-e07b8098-42c7-41cc-a98c-cb1bffe1f1d5.png)

The test_keopscore.py file tries to import "get_compiler_library" function from the keops package located in miniconda3 site-packages directory. When I navigate to the given location's config.py file and look for it manually, I see that there is no implementation for that function in the config.py file.

However, when I access the local keopscore directory in the cloned keops local repo, I can find a similar config.py file which does seem to have the implementation for the same function. 

I am not sure why this is the case. Would it be fine for me to copy this config.py file to the miniconda's site-package version of it or am I doing something wrong?

**Comment by initialneil** [comment]
@An-u-rag It seems that you did both `python setup.py install` and `python setup.py develop`.
Could you try pip uninstall pykeops and keopscore, and follow #281 step 5 to `python setup.py develop`. There should not be any source code in the site-packages other than a link file.

**Comment by An-u-rag** [comment]
@initialneil Yep that was the issue. Fixed it with pip uninstall. Thank you for all the help!

I'm not sure if this is a general concern or is it because of your changes to keops for windows but I am using a LazyTensor instantiation with Vi and Vj in my project and I seem to be getting these warnings from keops, is there a way I can suppress them? 

![image](https://user-images.githubusercontent.com/58253865/228435913-8ada7391-dc35-411a-ae03-330ceb0a3e6f.png)

**Comment by initialneil** [comment]
@An-u-rag Right cause this version is not officially tested and merged yet. These are normal logs for verbose purposes.

**Comment by An-u-rag** [comment]
@initialneil I tried working with it but I keep getting errors. Now, I can't even get the initial import to work due to a circular import error. I am not sure what is happening. 

I might just wait for the official release with windows support. Thanks for the help anyway!

**Comment by jeanfeydy** [comment]
Hi @Antoine-insa ,

Thanks for your interest in our library!
The `fcntl` dependency was kindly removed by @initialneil in the PR #281. I am currently working on testing and integrating his work but this takes some time because:
1. I am 100% new to development on Windows, and didn't even know how to get Python to work...
2. My only Windows computer is a workstation that is located in my office, without remote access. That's not optimal ;-)
3. I would like to add a Windows computer to our CI pipeline before completing the merge.

In any case, you should be able to try the branch by following the instructions [here](https://github.com/getkeops/keops/pull/281). Please feel free to let us know about your experience with it.
Best regards,
Jean

**Comment by Antoine-insa** [comment]
Many thanks @jeanfeydy , I will try the instructions you've pinpointed.
Best regards,
Antoine

**Comment by abrahamezzeddine** [comment]
@jeanfeydy  Hello,

do you know if there are any updates to have it work on Windows? Unfortunately, I get CUDA invalid memory something when I try it. I do not know how to solve that. I using PyTorch 2.5.1 and CUDA 12.4. 

Many thanks. Really looking forward to try this out!

**Comment by Lmorring** [comment]
Hello, can the current version run on windows computers now

**Comment by joanglaunes** [comment]
Hello @Lmorring ,
@Louis-Pujol has recently posted a new PR for Windows support : #421 .
It is still work in progress, but basically it should work already as is. It uses Cmake which requires to be installed before. If you can try it out and let us know if it works for you, it would be great!
