### ISSUE TITLE
This KeOps shared object has been compiled without cuda - Failed to build bindings

### ISSUE THREAD

**Issue by tdvginz** [getkeops/keops#61]
Hello friends, 
Thanks a lot for `keops`, amazing library, and great examples:)
Unfortunately, I couldn't build [this example](https://www.kernel-operations.io/keops/_auto_tutorials/gaussian_mixture/plot_gaussian_mixture.html), nor the `pykeops.test_torch_bindings()`

Following are my machine specs, and the error itself
 nvcc version - 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
gcc
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```
g++ 
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```
clang
```
clang version 8.0.0-3~ubuntu18.04.2 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
cmake 
```
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
pytorch 1.4

```
(testenv2) name@station:~/repos/docBert$ python
Python 3.7.7 (default, May  6 2020, 10:21:04) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykeops
>>> 
>>> pykeops.verbose = True
>>> pykeops.clean_pykeops()  
/home/name/.cache/pykeops-1.4-cpython-37/libKeOpstorchc33cb27a33.so has been removed.
/home/name/.cache/pykeops-1.4-cpython-37/libKeOpstorchc33cb27a33.cpython-37m-x86_64-linux-gnu.so has been removed.
>>> pykeops.test_torch_bindings() 
Compiling libKeOpstorch11f5758313 in /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313:
       formula: Sum_Reduction(SqNorm2(x - y),1)
       aliases: x = Vi(0,3); y = Vj(1,3); 
       dtype  : float32
... -- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /home/name/anaconda3/envs/testenv2/bin/x86_64-conda_cos6-linux-gnu-c++
-- Check for working CXX compiler: /home/name/anaconda3/envs/testenv2/bin/x86_64-conda_cos6-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using shared_obj_name: libKeOpstorch11f5758313
-- First i variables detected is 0
-- First j variables detected is 1
-- Compiled formula is Sum_Reduction(SqNorm2(x - y),1); auto x = Vi(0,3); auto y = Vj(1,3); where the number of args is 2.
-- Found PythonInterp: /home/name/anaconda3/envs/testenv2/bin/python3.7 (found suitable version "3.7.7", minimum required is "3.7") 
-- Found PythonLibs: /home/name/anaconda3/envs/testenv2/lib/libpython3.7m.so
-- pybind11 v2.3.dev1
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313

/usr/bin/cmake -H/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops -B/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/make -f CMakeFiles/Makefile2 libKeOpstorch11f5758313
make[1]: Entering directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
/usr/bin/cmake -H/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops -B/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles 4
/usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/libKeOpstorch11f5758313.dir/all
make[2]: Entering directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
/usr/bin/make -f CMakeFiles/keopslibKeOpstorch11f5758313.dir/build.make CMakeFiles/keopslibKeOpstorch11f5758313.dir/depend
make[3]: Entering directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
cd /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops /home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/keopslibKeOpstorch11f5758313.dir/DependInfo.cmake --color=
Dependee "/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/keopslibKeOpstorch11f5758313.dir/DependInfo.cmake" is newer than depender "/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/keopslibKeOpstorch11f5758313.dir/depend.internal".
Dependee "/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/keopslibKeOpstorch11f5758313.dir/depend.internal".
Scanning dependencies of target keopslibKeOpstorch11f5758313
make[3]: Leaving directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
/usr/bin/make -f CMakeFiles/keopslibKeOpstorch11f5758313.dir/build.make CMakeFiles/keopslibKeOpstorch11f5758313.dir/build
make[3]: Entering directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
[ 25%] Building CXX object CMakeFiles/keopslibKeOpstorch11f5758313.dir/keops/core/link_autodiff.cpp.o
/home/name/anaconda3/envs/testenv2/bin/x86_64-conda_cos6-linux-gnu-c++  -DC_CONTIGUOUS=1 -DMODULE_NAME=libKeOpstorch11f5758313 -DSUM_SCHEME=1 -DUSE_CUDA=0 -DUSE_DOUBLE=0 -DUSE_HALF=0 -D_GLIBCXX_USE_CXX11_ABI=0 -D__TYPEACC__=float -D__TYPE__=float -DkeopslibKeOpstorch11f5758313_EXPORTS -I/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops -I/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/keops -I/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 -I/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/torch/include -I/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/torch/include/torch/csrc/api/include  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/name/anaconda3/envs/testenv/include -DUSE_OPENMP -fopenmp -Wall -Wno-unknown-pragmas -fmax-errors=2 -O3 -DNDEBUG -O3 -fPIC   -include libKeOpstorch11f5758313.h -std=gnu++14 -o CMakeFiles/keopslibKeOpstorch11f5758313.dir/keops/core/link_autodiff.cpp.o -c /home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/keops/core/link_autodiff.cpp
[ 50%] Linking CXX shared library libKeOpstorch11f5758313.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/keopslibKeOpstorch11f5758313.dir/link.txt --verbose=1
/home/name/anaconda3/envs/testenv2/bin/x86_64-conda_cos6-linux-gnu-c++ -fPIC -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/name/anaconda3/envs/testenv/include -DUSE_OPENMP -fopenmp -Wall -Wno-unknown-pragmas -fmax-errors=2 -O3 -DNDEBUG -O3 -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/name/anaconda3/envs/testenv/lib -Wl,-rpath-link,/home/name/anaconda3/envs/testenv/lib -L/home/name/anaconda3/envs/testenv/lib -shared -Wl,-soname,libKeOpstorch11f5758313.so -o libKeOpstorch11f5758313.so CMakeFiles/keopslibKeOpstorch11f5758313.dir/keops/core/link_autodiff.cpp.o 
/usr/bin/cmake -E copy /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/libKeOpstorch11f5758313.so /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/../
make[3]: Leaving directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
[ 50%] Built target keopslibKeOpstorch11f5758313
/usr/bin/make -f CMakeFiles/libKeOpstorch11f5758313.dir/build.make CMakeFiles/libKeOpstorch11f5758313.dir/depend
make[3]: Entering directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
cd /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops /home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/libKeOpstorch11f5758313.dir/DependInfo.cmake --color=
Dependee "/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/libKeOpstorch11f5758313.dir/DependInfo.cmake" is newer than depender "/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/libKeOpstorch11f5758313.dir/depend.internal".
Dependee "/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles/libKeOpstorch11f5758313.dir/depend.internal".
Scanning dependencies of target libKeOpstorch11f5758313
make[3]: Leaving directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
/usr/bin/make -f CMakeFiles/libKeOpstorch11f5758313.dir/build.make CMakeFiles/libKeOpstorch11f5758313.dir/build
make[3]: Entering directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
[ 75%] Building CXX object CMakeFiles/libKeOpstorch11f5758313.dir/torch/generic/generic_red.cpp.o
/home/name/anaconda3/envs/testenv2/bin/x86_64-conda_cos6-linux-gnu-c++  -DC_CONTIGUOUS=1 -DMODULE_NAME=libKeOpstorch11f5758313 -DSUM_SCHEME=1 -DUSE_CUDA=0 -DUSE_DOUBLE=0 -DUSE_HALF=0 -D_GLIBCXX_USE_CXX11_ABI=0 -D__TYPEACC__=float -D__TYPE__=float -DlibKeOpstorch11f5758313_EXPORTS -I/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops -I/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/keops -I/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 -I/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/torch/include -I/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/pybind11/include -I/home/name/anaconda3/envs/testenv2/include/python3.7m  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/name/anaconda3/envs/testenv/include -DUSE_OPENMP -fopenmp -Wall -Wno-unknown-pragmas -fmax-errors=2 -O3 -DNDEBUG -O3 -fPIC -fvisibility=hidden   -flto -fno-fat-lto-objects -include torch_headers.h -std=gnu++14 -o CMakeFiles/libKeOpstorch11f5758313.dir/torch/generic/generic_red.cpp.o -c /home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.cpp
[100%] Linking CXX shared module libKeOpstorch11f5758313.cpython-37m-x86_64-linux-gnu.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/libKeOpstorch11f5758313.dir/link.txt --verbose=1
/home/name/anaconda3/envs/testenv2/bin/x86_64-conda_cos6-linux-gnu-c++ -fPIC -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/name/anaconda3/envs/testenv/include -DUSE_OPENMP -fopenmp -Wall -Wno-unknown-pragmas -fmax-errors=2 -O3 -DNDEBUG -O3 -Wl,-rpath,$ORIGIN -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/name/anaconda3/envs/testenv/lib -Wl,-rpath-link,/home/name/anaconda3/envs/testenv/lib -L/home/name/anaconda3/envs/testenv/lib -shared  -o libKeOpstorch11f5758313.cpython-37m-x86_64-linux-gnu.so CMakeFiles/libKeOpstorch11f5758313.dir/torch/generic/generic_red.cpp.o -Wl,-rpath,/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313 -flto libKeOpstorch11f5758313.so 
/usr/bin/strip /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/libKeOpstorch11f5758313.cpython-37m-x86_64-linux-gnu.so
/usr/bin/cmake -E copy /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/libKeOpstorch11f5758313.cpython-37m-x86_64-linux-gnu.so /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/../
make[3]: Leaving directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
[100%] Built target libKeOpstorch11f5758313
make[2]: Leaving directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'
/usr/bin/cmake -E cmake_progress_start /home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313/CMakeFiles 0
make[1]: Leaving directory '/home/name/.cache/pykeops-1.4-cpython-37/build-libKeOpstorch11f5758313'

Done.
Traceback (most recent call last):
  File "/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/test/install.py", line 55, in test_torch_bindings
    if torch.allclose(my_conv(x, y).view(-1), torch.tensor(expected_res).type(torch.float32)):
  File "/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 396, in __call__
    device_id, ranges, self.accuracy_flags, *args)
  File "/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 44, in forward
    result = myconv.genred_pytorch(tagCPUGPU, tag1D2D, tagHostDevice, device_id, ranges, *args)
RuntimeError: [KeOps] This KeOps shared object has been compiled without cuda support: 
 1) to perform computations on CPU, simply set tagHostDevice to 0
 2) to perform computations on GPU, please recompile the formula with a working version of cuda.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/test/install.py", line 66, in test_torch_bindings
    print(my_conv(x, y))
  File "/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 396, in __call__
    device_id, ranges, self.accuracy_flags, *args)
  File "/home/name/anaconda3/envs/testenv2/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 44, in forward
    result = myconv.genred_pytorch(tagCPUGPU, tag1D2D, tagHostDevice, device_id, ranges, *args)
RuntimeError: [KeOps] This KeOps shared object has been compiled without cuda support: 
 1) to perform computations on CPU, simply set tagHostDevice to 0
 2) to perform computations on GPU, please recompile the formula with a working version of cuda.
```

**Comment by tdvginz** [comment]
@bcharlier I'm so sorry, on the contrary! I deeply appreciate this library, It's simply that I thought that any added information would just be noise.

```
/testenv3) user@station:~/repos/docBert$ which nvcc/home/user/anaconda3/envs/testenv3/bin/nvcc
(testenv3) user@station:~/repos/docBert$ sudo ln -s /home/user/anaconda3/envs/testenv3/bin/nvcc /usr/local/cuda
```
But still the same result.
Also tried `pip uninstall` and `pip install --nocache`, after setting cuda path, if relevant.

**Comment by bcharlier** [comment]
is pytorch detecting your GPU ?

**Comment by tdvginz** [comment]
Yes
```
>>> torch.cuda.is_available()
True
```

**Comment by bcharlier** [comment]
and
```
$ whereis cuda
```

**Comment by bcharlier** [comment]
in any case /usr/local/cuda should link to the cuda root dir (not the nvcc binary).

**Comment by tdvginz** [comment]
```
whereis cudacuda: /usr/lib/cuda /usr/local/cuda
```
changed the pointer from the binary to `/usr/lib/cuda `

**Comment by bcharlier** [comment]
does it work ?

**Comment by tdvginz** [comment]
No:(

**Comment by tdvginz** [comment]
It worked! I needed to uninstall nvcc and reinstall it(toolkit) but now it works. probably condo pointers are not enough.

Unfortunatly, the GMM example you posted still doesn't work:(
