### ISSUE TITLE
ImportError: /home/mhorugan/.cache/pykeops-1.4-cpython-36/libKeOpstorch61259e55e7.cpython-36m-x86_64-linux-gnu.so: undefined symbol: ZN3c1010Dispatcher17findSchemaOrThrowEPKcS2"

### ISSUE THREAD

**Issue by mhorugan** [getkeops/keops#67]
Hello!

My name is Maanas, and I'm a researcher with the Faisal Lab at Simon Fraser University. I hope this message finds you well and safe during these times. 

I've been trying to use the KeOps Surface Registration [Python pipeline](https://www.kernel-operations.io/keops/_auto_tutorials/surface_registration/plot_LDDMM_Surface.html) to register some surfaces. However, when I execute the code, I receive the following messages:

"Traceback (most recent call last):
  File "surfRef.py", line 140, in <module>
    dataloss = lossVarifoldSurf(FS, VT, FT, GaussLinKernel(sigma=sigma))
  File "surfRef.py", line 101, in lossVarifoldSurf
    cst = (LT * K(CT, CT, NTn, NTn, LT)).sum()
  File "/home/mhorugan/.conda/envs/FOR_REAL/lib/python3.6/site-packages/pykeops/common/lazy_tensor.py", line 717, in _call_
    return self.callfun(*args, *self.variables, **self.kwargs)
  File "/home/mhorugan/.conda/envs/FOR_REAL/lib/python3.6/site-packages/pykeops/torch/generic/generic_red.py", line 396, in _call_
    device_id, ranges, self.accuracy_flags, *args)
  File "/home/mhorugan/.conda/envs/FOR_REAL/lib/python3.6/site-packages/pykeops/torch/generic/generic_red.py", line 22, in forward
    myconv = LoadKeOps(formula, aliases, dtype, 'torch', optional_flags).import_module()
  File "/home/mhorugan/.conda/envs/FOR_REAL/lib/python3.6/site-packages/pykeops/common/keops_io.py", line 52, in import_module
    return importlib.import_module(self.dll_name)
  File "/home/mhorugan/.conda/envs/FOR_REAL/lib/python3.6/importlib/_init_.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/mhorugan/.cache/pykeops-1.4-cpython-36/libKeOpstorch61259e55e7.cpython-36m-x86_64-linux-gnu.so: undefined symbol: ZN3c1010Dispatcher17findSchemaOrThrowEPKcS2"

My CUDA version is 10.0, and my PyTorch version is 1.4.0. Please let me know how I can resolve this issue and if I can provide any more information. I am running my code in a conda virtual environment, and I don't have any sudo permissions that I can use for resolving the messages I'm receiving.

**Comment by dancebean** [comment]
Hi @mhorugan , it seems your KeOps compilation is not successful.
Check the Requirement page here to see if all your tools have the correct version:
https://www.kernel-operations.io/keops/python/installation.html#requirements 
(e.g. g++ version >=7)

Fixing that solve the installation issue for me

**Comment by SamuelJoutard** [comment]
Hello,

I obtained a similar error message:

Traceback (most recent call last):
File "Code/non_local_feature_alignment/dataset_manager.py", line 143, in <module> preprocess_dist_map()
File "Code/non_local_feature_alignment/dataset_manager.py", line 117, in preprocess_dist_map D_ij = D_ij.min(dim=1)
File "/opt/conda/lib/python3.6/site-packages/pykeops/common/lazy_tensor.py", line 1465, in min return self.reduction("Min", axis=axis, **kwargs)
File "/opt/conda/lib/python3.6/site-packages/pykeops/common/lazy_tensor.py", line 560, in reduction return res()
File "/opt/conda/lib/python3.6/site-packages/pykeops/common/lazy_tensor.py", line 717, in __call__ return self.callfun(*args, *self.variables, **self.kwargs)
File "/opt/conda/lib/python3.6/site-packages/pykeops/torch/generic/generic_red.py", line 396, in __call__ device_id, ranges, self.accuracy_flags, *args)
File "/opt/conda/lib/python3.6/site-packages/pykeops/torch/generic/generic_red.py", line 22, in forward myconv = LoadKeOps(formula, aliases, dtype, 'torch', optional_flags).import_module()
File "/opt/conda/lib/python3.6/site-packages/pykeops/common/keops_io.py", line 52, in import_module return importlib.import_module(self.dll_name)
File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
File "<frozen importlib._bootstrap>", line 571, in module_from_spec
File "<frozen importlib._bootstrap_external>", line 922, in create_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /root/.cache/pykeops-1.4-cpython-36/libKeOpstorch0418f2b063.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

I checked all the requirements and everything is matched. 

Samuel

**Comment by jeanfeydy** [comment]
Hi @SamuelJoutard ,

Your problem seems to be different, and addressed in #59 . We will fix it with the next release - which should have been made weeks ago really, sorry about that. As far as this precise issue is concerned, I don't know: it probably comes from a compiler/path mismatch on @mhorugan 's machine, as noted by @dancebean (thanks!).

Best regards - and see you soon,
Jean

**Comment by SamuelJoutard** [comment]
Hi Jean,

Ok I missed this issue sorry. Thank you for the quick answer!

Best regards, see you soon.

Samuel

**Comment by jeanfeydy** [comment]
Hi @mhorugan ,

I assume that you solved the problem on your machine and close the issue. Feel free to re-open it if needed!

Best regards,
Jean
