### ISSUE TITLE
ImportError: /home/mo/.cache/pykeops-1.4-cpython-37/libKeOpstorch5f17c667de.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE  During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by chimoses** [getkeops/keops#71]
**Hello! 
I am very very interested in your project. But when I execute code in "Testing your installation" section from your "Python install" document. I met the bug and log information as follows:
(There are also some words, posted at the end, looking forward to your help.)**

Traceback (most recent call last):
  File "/home/mo/anaconda3/lib/python3.7/site-packages/pykeops/test/install.py", line 55, in test_torch_bindings
    if torch.allclose(my_conv(x, y).view(-1), torch.tensor(expected_res).type(torch.float32)):
  File "/home/mo/anaconda3/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 396, in __call__
    device_id, ranges, self.accuracy_flags, *args)
  File "/home/mo/anaconda3/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 22, in forward
    myconv = LoadKeOps(formula, aliases, dtype, 'torch', optional_flags).import_module()
  File "/home/mo/anaconda3/lib/python3.7/site-packages/pykeops/common/keops_io.py", line 52, in import_module
    return importlib.import_module(self.dll_name)
  File "/home/mo/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/mo/.cache/pykeops-1.4-cpython-37/libKeOpstorch5f17c667de.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mo/pro/KGA/REGCN/lab/keops_lab.py", line 52, in <module>
    test_installation()
  File "/home/mo/pro/KGA/REGCN/lab/keops_lab.py", line 40, in test_installation
    pykeops.test_torch_bindings()
  File "/home/mo/anaconda3/lib/python3.7/site-packages/pykeops/test/install.py", line 66, in test_torch_bindings
    print(my_conv(x, y))
  File "/home/mo/anaconda3/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 396, in __call__
    device_id, ranges, self.accuracy_flags, *args)
  File "/home/mo/anaconda3/lib/python3.7/site-packages/pykeops/torch/generic/generic_red.py", line 22, in forward
    myconv = LoadKeOps(formula, aliases, dtype, 'torch', optional_flags).import_module()
  File "/home/mo/anaconda3/lib/python3.7/site-packages/pykeops/common/keops_io.py", line 52, in import_module
    return importlib.import_module(self.dll_name)
  File "/home/mo/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/mo/.cache/pykeops-1.4-cpython-37/libKeOpstorch5f17c667de.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

**I see someone feedback similar problems in issues, but I still want to fully reflect my situation to you.
I very much hope to get help from your project and strive to promote your contribution and quote your contribution in future research. 
My requirement information is as follows.** 

- I have numpy and GPUtil packages in my Python Environment(Anaconda).
- g++ version is 7.5.0 and clang version is 8.0
- Cmake version is 3.17
- Cuda version is 10.2 (with nvcc include)and cudnn is 7.6.5 
- Pytorch version is 1.5.0

**Comment by bcharlier** [comment]
duplicate #59
