### ISSUE TITLE
Specific comandline compiler option unknown / support for nonstandard compiler location/name

### ISSUE THREAD

**Issue by nathanhack** [getkeops/keops#83]
Hello, I'm running Fedora 32 with cuda support by using https://negativo17.org/ but Keops doesn't seem to support this out of the box, which is fine, but I can't seem to find (although I'm not a cmake expert) a commandline arg to pass in to support it.

So not to cause aliasing negativo17.org changes the names of the gnu compilers specific to build cuda (since they're ancient) to the following :  `gcc` -> `cuda-gcc` and `g++` -> `cuda-c++`. 

----------
After installing I run the following  python script:
```
import pykeops
pykeops.clean_pykeops()          # just in case old build files are still present
pykeops.test_numpy_bindings()    # perform the compilation
```
From the commandline using this:
```
CC=/usr/bin/cuda-gcc CXX=/usr/bin/cuda-c++ python test.py
```
I get this error:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pykeops.test_numpy_bindings()    # perform the compilation
  File "/home/wnhack/.local/lib/python3.8/site-packages/pykeops/test/install.py", line 32, in test_numpy_bindings
    print(my_conv(x, y))
  File "/home/wnhack/.local/lib/python3.8/site-packages/pykeops/numpy/generic/generic_red.py", line 271, in __call__
    out = self.myconv.genred_numpy(tagCpuGpu, tag1D2D, 0, device_id, ranges, *args)
RuntimeError: [KeOps] This KeOps shared object has been compiled without cuda support: 
 1) to perform computations on CPU, simply set tagHostDevice to 0
 2) to perform computations on GPU, please recompile the formula with a working version of cuda.

```

From my limited understanding, I believe the following:
https://github.com/getkeops/keops/blob/0a5f2bf84bb7ac3b015a1528a9d1761151e02976/keops/cuda.cmake#L41

Would need to support the `-ccbin` parameter. 
As example, this compiles perfectly fine:
```
nvcc -ccbin=/usr/bin/cuda-c++   GetGpuProps.cu
```

But the following will not:
```
CC=/usr/bin/cuda-gcc CXX=/usr/bin/cuda-c++ nvcc GetGpuProps.cu 
```

It may be worth noting that pytorch and tensorflow GPU support work out of the box so I believe the runtime environment is correct.

**Comment by jeanfeydy** [comment]
Hi @nathanhack, 

Apologies for the very late answer...
@bcharlier, did we solve this issue with the v1.4.2 release?

Best regards,
Jean
