### ISSUE TITLE
ImportError: dynamic module does not define module export function

### ISSUE THREAD

**Issue by mhorugan** [getkeops/keops#84]
Hello!

I'm trying to execute the LDDMM surface [registration program](https://www.kernel-operations.io/keops/_auto_tutorials/surface_registration/plot_LDDMM_Surface.html) and I'm getting the error below. My file is called `surfRef.py` and I'm not sure why I'm getting an error about dynamic modules. Could it be a problem with my virtual conda environment?

Traceback (most recent call last):
  File "surfRef.py", line 140, in <module>
    dataloss = lossVarifoldSurf(FS, VT, FT, GaussLinKernel(sigma=sigma))
  File "surfRef.py", line 101, in lossVarifoldSurf
    cst = (LT * K(CT, CT, NTn, NTn, LT)).sum()
  File "/home/mhorugan/.conda/envs/Surface_Registration_Env/lib/python3.8/site-packages/pykeops/common/lazy_tensor.py", line 717, in __call__
    return self.callfun(*args, *self.variables, **self.kwargs)
  File "/home/mhorugan/.conda/envs/Surface_Registration_Env/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 395, in __call__
    out = GenredAutograd.apply(self.formula, self.aliases, backend, self.dtype,
  File "/home/mhorugan/.conda/envs/Surface_Registration_Env/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 22, in forward
    myconv = LoadKeOps(formula, aliases, dtype, 'torch', optional_flags).import_module()
  File "/home/mhorugan/.conda/envs/Surface_Registration_Env/lib/python3.8/site-packages/pykeops/common/keops_io.py", line 52, in import_module
    return importlib.import_module(self.dll_name)
  File "/home/mhorugan/.conda/envs/Surface_Registration_Env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit_libKeOpstorch8d4f5cc329)

**Comment by jeanfeydy** [comment]
Hi @mhorugan ,

Thanks for your interest in the library, and shape analysis in particular :-) 
The problem visibly comes from your compilation environment: does the [installation test](http://www.kernel-operations.io/keops/python/installation.html#testing-your-installation) work fine? 
Otherwise, the error message may help us to solve your issue.

Best regards,
Jean

**Comment by jeanfeydy** [comment]
Note that your problem is likely related to #2, #12 and [other issues](https://github.com/getkeops/keops/search?q=Import+Error%3A+dynamic+module+does+not+define+module+export+function&type=Issues), with conflicting versions of python, gcc and/or Pytorch in the same virtual environment.

**Comment by jeanfeydy** [comment]
Hi @mhorugan ,

I assume that you solved the problem on your machine. If needed, feel free to re-open the issue!

Best regards,
Jean
